### ISSUE TITLE
考虑是否对接口进行加密保护

### ISSUE THREAD

**Issue by Jzow** [Charity-Software-Organization/CSO-Portal-Platform#1]
如果需要的话可以使用Spring Security

**Comment by jinyubo35** [comment]
所有的信息基本都是要对外展示的，个人建议不需要加密------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;James&amp;nbsp;Zow&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月25日(星期四) 中午11:07
收件人:&nbsp;&quot;Charity-Software-Organization/CSO-Portal-Platform&quot;<CSO-Portal-Platform@noreply.github.com&gt;;
抄送:&nbsp;&quot;jinyubo35&quot;<1990009696@qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [Charity-Software-Organization/CSO-Portal-Platform] 考虑是否对接口进行加密保护 (#1)
